### ISSUE TITLE
Exception trying to fetch the latest version

### ISSUE THREAD

**Issue by LTHPKBTE** [TechnicJelle/BlueMapOfflinePlayerMarkers#43]
```
[00:10:58 ERROR]: [BlueMap] BlueMapAPI: A BlueMapAPI listener threw an exception (onEnable)!
java.util.concurrent.CompletionException: Exception trying to fetch the latest version
        at BlueMapOfflinePlayerMarkers-2.9.jar/com.technicjelle.UpdateChecker.fetchLatestVersion(UpdateChecker.java:87) ~[BlueMapOfflinePlayerMarkers-2.9.jar:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
Caused by: java.io.IOException: Did not get a redirect
        at BlueMapOfflinePlayerMarkers-2.9.jar/com.technicjelle.UpdateChecker.fetchLatestVersion(UpdateChecker.java:80) ~[BlueMapOfflinePlayerMarkers-2.9.jar:?]
        ... 7 more
```
In some areas, the network environment may not allow the plug-in to check for updates.
Is there any way to disable its update check?

**Comment by TechnicJelle** [comment]
This is currently not possible.
I'm going to close this issue here, and ask you to repost it in here: https://github.com/TechnicJelle/UpdateCheckerJava, so I can keep track of the feature request where it belongs.

**Comment by TechnicJelle** [comment]
I happened to need this feature during the development of [BlueMapSpawnMarker](https://github.com/TechnicJelle/BlueMapSpawnMarker) and [BlueMapNativeAddonTemplate](https://github.com/TechnicJelle/BlueMapNativeAddonTemplate) today, so I updated the Update Checker to now be able to be disabled!
I will now have to go through every single of my plugins (that's like 20 about now!) and change the version of the update checker those use.
I hope to be able to do that this week...

**Comment by TechnicJelle** [comment]
Actually, I'll reopen it to serve as a reminder for myself

**Comment by TechnicJelle** [comment]
Done in [`4deaeaf`](https://github.com/TechnicJelle/BlueMapOfflinePlayerMarkers/commit/4deaeafc6b88b9784a429fb286df94f6bec233dd#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R97) where I updated the Update Checker.

If you want to disable the update checker, you can do so by passing `-Dtechnicjelle.updatechecker.disabled` as a JVM argument.\
Example: `java -Dtechnicjelle.updatechecker.disabled -jar server.jar`

**Comment by TechnicJelle** [comment]
Please let me know if it works, @LTHPKBTE!

**Comment by LTHPKBTE** [comment]
> Please let me know if it works, @LTHPKBTE!

I had to terminate my server due to academic reasons and may not be able to test this any more. 
Thank you for your work!

-Automatic translation, please ignore grammatical errors.

**Comment by TechnicJelle** [comment]
Ah. I'm sorry to hear that.
You're welcome! :)

And thank you for using my addon :)
